---
title: "R Notebook"
output: html_notebook
---


```{r}

require(maps)  #loading maps package
require(mapdata) #loading mapdata package
library(ggplot2) #ggplot2 package
library(readxl) #package for read .xlsx file
library(ggthemes) #package for ggplot2 theme
library(ggrepel) #extendig the plotting package ggplot2 for maps
library(dplyr)
library(tidyr)
library(scales)

```


```{r}

setwd("C:\\Users\\joshu\\Documents\\git\\shiny_redd\\redd_indonesia") #set your own directory
mydata<- read_xlsx("data\\dummy.xlsx") #assign the data to "mydata"

View(mydata) #view the data, notice the column of "latitude","longitude", "woe_label"

```



```{r}
global <- map_data("world") #World longitude and latitude data 

View(global) #view the data and notice the column of long, lat, and group

gg1 <- ggplot() + 
  geom_polygon(data = global, aes(x=long, y = lat, group = group), 
               fill = "red", color = "red") + 
  coord_fixed(1.3) 
#you can change the "fill" (fill color) and the "color" (line color)

print(gg1) #show the plot
```


```{r}
gg1 <- ggplot() +
            geom_polygon(data = global, aes(x=long, y = lat, group = group),
                         fill = "brown1", color = "gray80") +
            coord_fixed(1.3)

        Indo <-gg1 + xlim(94,142) + ylim(-11,7.5) +
            geom_point(data = mydata, aes(x = longitude, y = latitude),
                       color = "blue", size=2, alpha = 0.5, show.legend = F) +
            geom_text_repel(data = mydata, aes(x = longitude, y = latitude,
                                               label= woe_label), color = "grey30",show.legend=F, size=2.5) +
            theme_map()

        print(Indo)
        ggsave("map.png")
        
```


```{r}
firedata <- read_xlsx("data\\Indonesia_fire.xlsx") 
firedata <- transform(firedata, period = as.Date(as.character(period), "%Y"))
firedata$period <- format(firedata$period, format="%Y")
firedata$wildfire_emissions_co2e <- firedata$wildfire_emissions * 1000000
freldata <- read_xlsx("data\\Indonesia_frel.xlsx") 
freldata$period <- format(freldata$period, format="%Y")
reductdata <- read_xlsx("data\\Indonesia_er.xlsx") 
reductdata$period <- format(reductdata$period, format="%Y")

all_data <- firedata %>% 
  full_join(freldata) %>% 
  full_join(reductdata) %>%
  arrange(period)
```

```{r}

p1 <-ggplot(firedata, aes(x=as.double(period), y=wildfire_emissions)) +
            geom_point(size=3, shape=23, color="purple3", fill="purple3") +
            geom_smooth(method = "auto", span = as.double(0.5), level=0.95) +
            theme_minimal() +
            theme(axis.title.x = element_text(vjust=1), axis.title.y.left = element_text(vjust=+10)) +
            labs(title = "Simple Wildfire Emissions plot",
                 subtitle = "(2000-2020)",
                 caption = "Data from CAMS GFAS and FREL submissions (check data description for more details)",
                 tag = "Figure 1",
                 x = "Period", y = "Carbon Emissions (Megatonnes)") 

p1

ggsave("plot1.png")
```



```{r}
# Data preparation

some_data <- subset(all_data, period > 2000)
df <- some_data %>%
  select(period, total_annual_emissions, frel_reference) %>%
  gather(key = "Variables", value = "Values", -period)

df$Variables[df$Variables == "total_annual_emissions"] <- "Total Emissions"
df$Variables[df$Variables == "frel_reference"] <- "FREL"
df$Values <- df$Values/1000000

firedata1 <- firedata[df[["period"]] >= "2012", ]
firedata2 <- firedata[df[["period"]] < "2012", ]
firedata1 <- subset(firedata, period >= 2012)
firedata2 <- subset(firedata, period < 2012)

```



```{r}
# Visualization
g <- ggplot(df, aes(x = as.double(period), y = Values)) + 
  geom_line(size=1, aes(color = Variables)) + 
  scale_color_manual(values = c("goldenrod1", "coral1", "black", "black")) +
  labs(title = "Simple REDD+ plot",
    subtitle = "(2000-2020)",
    caption = "Data from CAMS GFAS and FREL submissions (check data description for more details)",
    tag = "Figure 2",
    x = "Period", y = "Carbon Emissions/Reference Levels (Megatonnes)") +
  geom_point(size=2, aes(color=Variables)) +
  theme_minimal() +
  theme(legend.position="top") +
  theme(axis.title.x = element_text(vjust=1), axis.title.y.left = element_text(vjust=+10)) +
  scale_x_continuous(breaks= pretty_breaks())

g <- g + geom_point(data=firedata1, aes(x=as.double(period), y=wildfire_emissions, fill = "Fires pre-REDD+"), size=2, shape=23) + 
  scale_shape_identity() + geom_smooth(data = firedata1, aes(x=as.double(period), y=wildfire_emissions), method = lm, span = 0.5, level=0.95) + 
  geom_point(data=firedata2, aes(x=as.double(period), y=wildfire_emissions, fill = "Fires during REDD+"), size=2, shape=23) + 
  geom_smooth(data = firedata2, aes(x=as.double(period), y=wildfire_emissions), method = lm, span = 0.5, level=0.95)

g

ggsave("plot2.png")

```



```{r}
# Data preparation
 
df <- all_data %>%
  select(period, deforestation_reference, forestdegradation_reference, peatdecomposition_reference, deforestation_actual, forestdegradation_actual, peatdecomposition_actual) %>%
  gather(key = "Variables", value = "Values", -period)

df$Variables[df$Variables == "wildfire_emissions_co2e"] <- "Wildfire Emissions"
df$Variables[df$Variables == "deforestation_reference"] <- "Deforestation Reference"
df$Variables[df$Variables == "forestdegradation_reference"] <- "Degradation Reference"
df$Variables[df$Variables == "peatdecomposition_reference"] <- " Peat decomposition Reference"
df$Variables[df$Variables == "deforestation_actual"] <- "Deforestation"
df$Variables[df$Variables == "forestdegradation_actual"] <- "Forest degradation"
df$Variables[df$Variables == "peatdecomposition_actual"] <- "Forest peat decomposition"
df$Values <- df$Values/1000000
df <- df[!(df[["period"]] >= "2012" & df[["Variables"]] == "Deforestation"), ]
df <- df[!(df[["period"]] >= "2012" & df[["Variables"]] == "Forest degradation"), ]
df <- df[!(df[["period"]] >= "2012" & df[["Variables"]] == "Forest peat decomposition"), ]
df <- df[df[["period"]] >= "1990" & df[["period"]] <= "2020", ]

firedata1 <- firedata[df[["period"]] >= "2012", ]
firedata2 <- firedata[df[["period"]] < "2012", ]
firedata1 <- subset(firedata, period >= 2012)
firedata2 <- subset(firedata, period < 2012)



```

```{r}

# Visualization
g <- ggplot(df, aes(x = as.double(period), y = Values)) +
  geom_line(size=1, aes(color = Variables)) +
  scale_color_manual(values = c("darkred", "red", "blue3", "hotpink", "darkorchid1", "cornflowerblue", "red", "green")) +
  labs(title = "Comparing Emissions With Reference Levels In Indonesia",
    subtitle = "(1990-2020)",
    caption = "Data from CAMS GFAS and FREL submissions (check data description for more details)",
    tag = "Figure 3",
    x = "Period", y = "Carbon Emissions/Reference Levels (Megatonnes)") +
  geom_point(size=2, aes(color=Variables)) +
  theme_minimal() +
  theme(legend.position="top") +
  theme(axis.title.x = element_text(vjust=1), axis.title.y.left = element_text(vjust=+10)) +
  scale_x_continuous(breaks= pretty_breaks())


g <- g + geom_point(data=firedata1, aes(x=as.double(period), y=wildfire_emissions, fill = "Fires pre-REDD+"), size=2, shape=23) + 
  scale_shape_identity() + geom_smooth(data = firedata1, aes(x=as.double(period), y=wildfire_emissions), method = lm, span = 0.5, level=0.95) + 
  geom_point(data=firedata2, aes(x=as.double(period), y=wildfire_emissions, fill = "Fires during REDD+"), size=2, shape=23) + 
  geom_smooth(data = firedata2, aes(x=as.double(period), y=wildfire_emissions), method = lm, span = 0.5, level=0.95)

g

ggsave("plot3.png")
```




```{r}
# Data preparation

df <- all_data %>%
  select(period, wildfire_emissions_co2e, frel_reference, deforestation_actual,
         forestdegradation_actual, peatdecomposition_actual, total_annual_emissions) %>%
  gather(key = "Variables", value = "Values", -period)
 
df$Variables[df$Variables == "wildfire_emissions_co2e"] <- "Wildfires"
df$Variables[df$Variables == "frel_reference"] <- "FREL"
df$Variables[df$Variables == "deforestation_actual"] <- "Deforestation"
df$Variables[df$Variables == "forestdegradation_actual"] <- "Forest degradation"
df$Variables[df$Variables == "peatdecomposition_actual"] <- "Forest peat decomposition"
df$Variables[df$Variables == "total_annual_emissions"] <- "Total emissions"
df$Values <- df$Values/1000000

 
```


```{r}
# Visualization
g <- ggplot(df, aes(x = as.double(period), y = Values)) + 
  geom_line(size=1, aes(color = Variables)) + 
  scale_color_manual(values = c("red", "steelblue", "darkgreen", "goldenrod1", "coral1", "purple3")) +
  labs(title = "Total Forest Carbon Emissions In Indonesia",
    subtitle = "(1990-2020)",
    caption = "Data from CAMS GFAS and FREL submissions (check data description for more details)",
    tag = "Figure 4",
    x = "Period", y = "Carbon Emissions Equivalent (Megatonnes)") +
  geom_point(size=2, aes(color=Variables)) +
  theme_minimal() +
  theme(legend.position="top") +
  theme(axis.title.x = element_text(vjust=1), axis.title.y.left = element_text(vjust=+10)) +
  scale_x_continuous(breaks= pretty_breaks())
  
g

ggsave("plot4.png")
```

```{r}
install.packages('rsconnect')


```

